### ISSUE TITLE
magicbook i5-8250U dw1820a适配及问题

### ISSUE THREAD

**Issue by duanmuweiyu** [buseQ/magicbook-hackintosh-opencore-i7-8550u-#1]
#### 1. 安装适配
1. 按照教程安装，先在bios里面屏蔽安全启动，屏蔽无线和蓝牙
2. dw1820a(CN-08PKF4)需要屏蔽5个针脚
3. i5-8250屏蔽CpuFriend相关的驱动，我直接重命名驱动文件，在config.plist里面删除CpuFriend相关的配置
4. dw1820a 5G 显示300M的问题，需要添加启动项 **brcmfx-country=#a**，注意这个用的是opencore，不能用Clover Configurator来添加，用vscode打开config.plist修改
```xml
<key>boot-args</key>
<string>nv_disable=1 dart=0 bpr_probedelay=200 bpr_initialdelay=400 bpr_postresetdelay=400 brcmfx-country=#a</string>
```
重启即可达到满速

#### 2. 目前碰到的问题
1. 不支持hidpi
2. 触控板偶尔失效
3. 其他遇到问题后续补充

非常感谢作者提供EFI

**Comment by buseQ** [comment]
1.hidpi不打算支持，你可以参照其他开启hidpi的帖子。
2.触摸板失效的问题，试下摁F11，貌似F11在mac下是触摸板的开关键
3.无线网卡dw1802a我的是CN-096JNT版本，无需屏蔽针脚

**Comment by buseQ** [comment]
> #### 1. 安装适配
> 1. 按照教程安装，先在bios里面屏蔽安全启动，屏蔽无线和蓝牙
> 2. dw1820a(CN-08PKF4)需要屏蔽5个针脚
> 3. i5-8250屏蔽CpuFriend相关的驱动，我直接重命名驱动文件，在config.plist里面删除CpuFriend相关的配置
> 4. dw1820a 5G 显示300M的问题，需要添加启动项 **brcmfx-country=#a**，注意这个用的是opencore，不能用Clover Configurator来添加，用vscode打开config.plist修改
> 
> ```
> <key>boot-args</key>
> <string>nv_disable=1 dart=0 bpr_probedelay=200 bpr_initialdelay=400 bpr_postresetdelay=400 brcmfx-country=#a</string>
> ```
> 
> 重启即可达到满速
> 
> #### 2. 目前碰到的问题
> 1. 不支持hidpi
> 2. 触控板偶尔失效
> 3. 其他遇到问题后续补充
> 
> 非常感谢作者提供EFI

1.hidpi不打算支持，你可以参照其他开启hidpi的帖子。
2.触摸板失效的问题，试下摁F11，貌似F11在mac下是触摸板的开关键
3.无线网卡dw1802a我的是CN-096JNT版本，无需屏蔽针脚

**Comment by duanmuweiyu** [comment]
最近升级到10.15.3，触控板又罢工了，恢复方式参考这篇[文章](http://bbs.pcbeta.com/viewthread-1810079-2-1.html) 34F
> 是mac /S/L/E目录下自带的和appleIntelLpssI2C.kext和appleIntelLpssI2CController.kext和Voodooi2c冲突了，删掉后重建缓存就可以了

删除的时候报只读文件系统无法删除，解决办法是
`sudo mount -uw /`
